---
title: "Cost-effectiveness for global health targets"
author: Robin Blythe, Tori Oliver, Natalie Carvalho, Sumie Leung, Sant-Rayn Pasricha, Michael Bode
format: docx
editor: visual
bibliography: references.bib
---

# Resetting global health targets: Case study of the SDG target for anaemia

## Background

The Sustainable Development Goals (SDGs) were released in 2015 as a set of aspirational targets for the each country to aspire to, including the elimination of poverty, gender inequality, and hunger. Within these broader aspirational goals, clear targets were set for certain measures. Sustainable Development Goal 2, Zero Hunger, contains a clear directive to reduce the prevalence of anaemia in women of reproductive age by 50%. As of 2019, it was evident that the current rate of anaemia reductions was insufficient to reach the 2030 goal. [@Stevens2022] Given that anaemia is a highly multifactorial disease and is difficult to treat, [@Daru2022] it may be prudent to assess how targets are set for global health directives.

A fundamental principle of health economics is that every health intervention has an opportunity cost. Every dollar spent on reducing anaemia prevalence is competing with expenditures not only in healthcare, but other services such as housing and transportation, which may also positively or negatively impact human health. This makes it imperative to understand the costs of different anaemia reduction strategies, their impact on anaemia prevalence, and the value of these strategies compared to other healthcare interventions. Spending a disproportionate amount of the national healthcare budget on anaemia can adversely affect human health when that funding could be used for proportionally greater improvements in health-related quality of life.

The aim of this study is to demonstrate a new approach to target setting in global health interventions using cost-effectiveness analysis. In this paper, we show that each country has significant differences in their ability to fund anaemia reduction strategies, and these differences can create large gaps between the 50% target established by the SDGs and the maximum possible cost-effective reduction. We suggest that future global health targets are based on data, using available evidence to determine how much health funding each country can practically devote to a target given the effectiveness and cost of the interventions required to reach it.

## Methods

We used publicly available data to simulate the potential costs, outcomes, and cost-effectiveness of the World Health Organisation (WHO) recommended strategies for treating anaemia in 192 United Nations member countries. We obtained country-specific estimates for the maximum possible reduction in anaemia based on cost-effective treatments, and aggregated these estimates to obtain a global target.

### Anaemia reduction strategies

Included strategies based on WHO recommendations

### Data

We obtained prevalence data for the prevalence of mild, moderate and severe anaemia in 2021 from the Global Burden of Disease (GBD) study.

Coverage

Costs
